---
# TODO(inc0): Gates don't seem to have ufw executable, check for it instead of ignore errors
- block:
    - name: Set firewall default policy
      become: True
      ufw:
        state: disabled
        policy: allow
      when: ansible_facts.os_family == 'Debian'
      ignore_errors: yes

    - name: Check if firewalld is installed
      command: rpm -q firewalld
      register: firewalld_check
      changed_when: false
      failed_when: firewalld_check.rc > 1
      args:
        warn: false
      when: ansible_facts.os_family == 'RedHat' or ansible_facts.os_family == 'Kylin Linux Advanced Server'

    - name: Disable firewalld
      become: True
      service:
        name: "{{ item }}"
        enabled: false
        state: stopped
      with_items:
        - firewalld
      when:
        - ansible_facts.os_family == 'RedHat' or ansible_facts.os_family == 'Kylin Linux Advanced Server'
        - firewalld_check.rc == 0
  when: disable_firewall | bool

- import_role:
    name: openstack.kolla.packages

- import_role:
    name: openstack.kolla.docker
