---
- name: Install packages
  vars:
    pkg_installs: >-
      {{ ubuntu_pkg_install if ansible_facts.os_family == 'Debian'
         else openeuler_pkg_install if ansible_facts.distribution == 'openEuler'
         else kylin_server_pkg_install if ansible_facts.distribution == 'Kylin Linux Advanced Server'
         else redhat_pkg_install }}
  package:
    name: "{{ pkg_installs | select | list }}"
    cache_valid_time: "{{ apt_cache_valid_time if ansible_facts.os_family == 'Debian' else omit }}"
    update_cache: "{{ True if ansible_facts.os_family == 'Debian' else omit }}"
    state: present
  become: true

- name: Remove packages
  vars:
    pkg_removals: >-
      {{ ubuntu_pkg_removals if ansible_facts.os_family == 'Debian'
         else kylin_server_pkg_removals if ansible_facts.distribution == 'Kylin Linux Advanced Server'
         else redhat_pkg_removals }}
  package:
    name: "{{ pkg_removals | select | list }}"
    state: absent
  become: true
