---
# Apt cache TTL in seconds.
apt_cache_valid_time: 3600

enable_multipathd: false

# Whether the nova_libvirt container is enabled.
enable_nova_libvirt_container: false

ubuntu_pkg_install:
 - git
 - iputils-ping
 - "{% if enable_multipathd|bool %}sg3-utils-udev{% endif %}"
 - tzdata

openeuler_pkg_install:
 - python3-docker

redhat_pkg_install:
 - git
 - iputils
 - sudo

kylin_server_pkg_install:
 - git
 - iputils
 - sudo

ubuntu_pkg_removals:
 - lxd
 - lxc
 - "{% if enable_nova_libvirt_container | bool %}libvirt-bin{% endif %}"
 - open-iscsi

redhat_pkg_removals:
 - "{% if enable_nova_libvirt_container | bool %}libvirt{% endif %}"
 - "{% if enable_nova_libvirt_container | bool %}libvirt-daemon{% endif %}"
 - "{% if enable_nova_libvirt_container | bool %}iscsi-initiator-utils{% endif %}"

kylin_server_pkg_removals:
 - "{% if enable_nova_libvirt_container | bool %}libvirt{% endif %}"
 - "{% if enable_nova_libvirt_container | bool %}libvirt-daemon{% endif %}"
 - "{% if enable_nova_libvirt_container | bool %}iscsi-initiator-utils{% endif %}"
