---
- name: Ensure yum repos directory exists
  file:
    path: /etc/yum.repos.d/
    state: directory
    recurse: yes
  become: True

- name: Enable docker yum repository
  yum_repository:
    name: docker
    description: Docker main Repository
    baseurl: "{{ docker_yum_baseurl }}"
    gpgcheck: "{{ docker_yum_gpgcheck | bool }}"
    gpgkey: "{{ docker_yum_gpgkey }}"
    # NOTE(yoctozepto): required to install containerd.io due to runc being a
    # modular package in CentOS 8 see:
    # https://bugzilla.redhat.com/show_bug.cgi?id=1734081
    module_hotfixes: true
  become: True

- name: Install docker rpm gpg key
  rpm_key:
    state: present
    key: "{{ docker_yum_gpgkey }}"
  become: True
  when: docker_yum_gpgcheck | bool
