---
redhat_os_family:
  - RedHat
  - Kylin Linux Advanced Server

debian_os_family:
  - Debian

ceph_version: "quincy"
epel_version: "9"
ceph_url: "https://download.ceph.com"

# Ceph APT repository configuration.
ceph_apt_url: "{{ ceph_url }}/debian-{{ ceph_version }}/"
ceph_apt_repo: "deb {{ ceph_apt_url }} {{ ansible_facts.distribution_release }} main"
ceph_apt_key_file: "{{ ceph_url }}/keys/release.gpg"
ceph_apt_key_id: "460F3994"
ceph_apt_package: "ceph-common"

# Ceph Yum repository configuration.
ceph_yum_url: "{{ ceph_url }}/rpm-{{ ceph_version }}/"
ceph_yum_baseurl: "{{ ceph_yum_url }}el{{ epel_version }}/$basearch/"
ceph_yum_gpgkey: "{{ ceph_url }}/keys/release.asc"
ceph_yum_gpgcheck: true
ceph_yum_package: "ceph-common"
epel_yum_package: "epel-release"

customize_etc_hosts: True

create_kolla_user: False

kolla_user: "kolla"
kolla_group: "kolla"

change_selinux: True

selinux_state: "permissive"

# If true, the host firewall service (firewalld or ufw) will be disabled.
disable_firewall: True

git_http_proxy: ""
git_https_proxy: ""

node_config_directory: "/etc/kolla"

